from unittest import TestCase

from ASD1.lesson05.task05 import Queue
from ASD1.test.lesson05.task05_02 import queue_rotate, queue_reverse
from ASD1.test.lesson05.queue_by_stacks import QueueByStacks
from ASD1.test.lesson05.round_queue import RoundQueue

class Test(TestCase):
    def test_queue_rotate(self):
        q = Queue()
        q.enqueue(1)
        q.enqueue(2)
        q.enqueue(3)
        q.enqueue(4)
        q.enqueue(5)
        queue_rotate(q, 3)
        self.assertEqual(q.dequeue(), 4)
        self.assertEqual(q.dequeue(), 5)
        self.assertEqual(q.dequeue(), 1)
        self.assertEqual(q.dequeue(), 2)
        self.assertEqual(q.dequeue(), 3)

    def test_size(self):
        q = QueueByStacks()
        q.enqueue(1)
        q.enqueue(2)
        self.assertEqual(2, q.size())

    def test_enqueue(self):
        queue = QueueByStacks()
        queue.enqueue(1)
        self.assertEqual(1, queue.size())
        queue.enqueue(2)
        self.assertEqual(2, queue.size())
        queue.enqueue(3)
        self.assertEqual(3, queue.size())

    def test_dequeue(self):
        queue = QueueByStacks()
        queue.enqueue(1)
        self.assertEqual(1, queue.size())
        queue.enqueue(2)
        self.assertEqual(2, queue.size())
        queue.enqueue(3)
        self.assertEqual(3, queue.size())

        self.assertEqual(1, queue.dequeue())
        self.assertEqual(2, queue.size())
        self.assertEqual(2, queue.dequeue())
        self.assertEqual(1, queue.size())
        self.assertEqual(3, queue.dequeue())
        self.assertEqual(0, queue.size())
        self.assertIsNone(queue.dequeue())
        self.assertEqual(0, queue.size())

        queue.enqueue(1)
        self.assertEqual(1, queue.size())
        queue.enqueue(2)
        self.assertEqual(2, queue.size())
        queue.enqueue(3)
        self.assertEqual(3, queue.size())
        self.assertEqual(1, queue.dequeue())
        self.assertEqual(2, queue.size())
        queue.enqueue(4)
        queue.enqueue(5)
        self.assertEqual(4, queue.size())
        self.assertEqual(2, queue.dequeue())
        self.assertEqual(3, queue.size())
        self.assertEqual(3, queue.dequeue())
        self.assertEqual(2, queue.size())
        self.assertEqual(4, queue.dequeue())
        self.assertEqual(1, queue.size())
        self.assertEqual(5, queue.dequeue())
        self.assertEqual(0, queue.size())

    def test_reverse(self):
        queue = Queue()
        queue.enqueue(1)
        queue.enqueue(2)
        queue.enqueue(3)
        self.assertEqual(3, queue.size())
        queue_reverse(queue)
        self.assertEqual(3, queue.size())
        self.assertEqual(3, queue.dequeue())
        self.assertEqual(2, queue.dequeue())
        self.assertEqual(1, queue.dequeue())

    def test_round_queue(self):
        queue = RoundQueue(5)
        queue.enqueue(11)
        self.assertEqual(1, queue.size())
        self.assertEqual(11, queue.queue[0])
        self.assertEqual(0, queue.head_index)
        self.assertEqual(0, queue.tail_index)
        queue.enqueue(22)
        self.assertEqual(2, queue.size())
        self.assertEqual(11, queue.queue[0])
        self.assertEqual(22, queue.queue[1])
        self.assertEqual(0, queue.head_index)
        self.assertEqual(1, queue.tail_index)
        queue.enqueue(33)
        self.assertEqual(3, queue.size())
        self.assertEqual(11, queue.queue[0])
        self.assertEqual(22, queue.queue[1])
        self.assertEqual(33, queue.queue[2])
        self.assertEqual(0, queue.head_index)
        self.assertEqual(2, queue.tail_index)
        queue.enqueue(44)
        self.assertEqual(4, queue.size())
        self.assertEqual(11, queue.dequeue())
        self.assertEqual(3, queue.size())
        self.assertEqual(11, queue.queue[0])
        self.assertEqual(22, queue.queue[1])
        self.assertEqual(33, queue.queue[2])
        self.assertEqual(44, queue.queue[3])
        self.assertEqual(1, queue.head_index)
        self.assertEqual(3, queue.tail_index)


        queue.enqueue(55)
        queue.enqueue(66)
        self.assertEqual(5, queue.size())
        self.assertEqual(1, queue.head_index)
        self.assertEqual(0, queue.tail_index)

        with self.assertRaises(Exception) as cm:
            queue.enqueue(77)
        self.assertEqual(str(cm.exception), 'Queue overflow')

        self.assertEqual(22, queue.dequeue())
        self.assertEqual(2, queue.head_index)
        self.assertEqual(0, queue.tail_index)
        queue.enqueue(77)
        self.assertEqual(1, queue.tail_index)
        self.assertEqual(33, queue.dequeue())
        self.assertEqual(3, queue.head_index)
        self.assertEqual(1, queue.tail_index)
        queue.enqueue(88)
        self.assertEqual(3, queue.head_index)
        self.assertEqual(2, queue.tail_index)
        self.assertEqual(44, queue.dequeue())
        self.assertEqual(55, queue.dequeue())
        self.assertEqual(66, queue.dequeue())
        self.assertEqual(77, queue.dequeue())
        self.assertEqual(88, queue.dequeue())

        self.assertIsNone(queue.dequeue())
        self.assertEqual(0, queue.size())
        queue.enqueue(99)
        self.assertEqual(1, queue.size())
        self.assertEqual(99, queue.queue[0])
        self.assertEqual(0, queue.head_index)
        self.assertEqual(0, queue.tail_index)
